### PR TITLE
fixing the first file ITSPARK:1

### PR DESCRIPTION
**Pull request by sush-19**
reverting the first file  to fix an issue ITSPARK:1

### CODE REVIEW

**Comment by mahesh3267** [comment]
lint testing must be starting with #, should look like this 
```#testing```

**Comment by Sarithachinni** [comment]
This is my first comment

**Comment by sush-19** [comment]
I fixed the issue

**Comment by mahesh3267** [comment]
@sush-19  : you are good to merge the changes.  - please go ahead.

**Pull request merged**
